---
#- name: Configure IAM update policy
#  set_fact:
#    custom_iam: false

- name: Create Cluster
  shell: "kops create cluster --zones=ap-southeast-1a --node-count=3 --master-count=1 --node-size=t2.micro --master-size=t2.medium --ssh-public-key=/root/.ssh/id_rsa.pub --name=kube.ical.host --state=s3://belajarkubecoy"

#- name: Create Cluster
#  shell: 
#    "kops create cluster --zones=ap-southeast-1a --node-count=3 --master-count=1 --node-size=t2.micro --master-size=t2.medium --ssh-public-key=/root/.ssh/id_rsa.pub --name=kube.ical.host --state=s3://belajarkubecoy"
#  register: kopscreate
#  tags: kopscreate

- debug: msg="{{kopscreate/stdout}}"

- name: Update Cluster
  shell: "kops update cluster {{ KOPS_CLUSTER_NAME }} --state {{ KOPS_STATE_STORE }} --yes --admin"
